### ISSUE TITLE
Whonix 15 KVM has both gateway and workstation rolled into single libvirt file

### ISSUE THREAD

**Issue by MindMount** [bcl/whonix-user-qemu#1]
Whonix 15 KVM has both gateway and workstation rolled into a single unified ova libvirt file.
When I try to run the script with the unified OVA I get this error:

`$ '/home/user/Downloads/Whonix/QEMU/whonix-user-qemu-master/run-workstation' '/home/user/Downloads/Whonix/QEMU/whonix-user-qemu-master/Whonix-XFCE-15.0.0.0.9.libvirt' 
SMP = 2
MEM = 2048
WARNING: Image format was not specified for '/home/user/Downloads/Whonix/QEMU/whonix-user-qemu-master/Whonix-XFCE-15.0.0.0.9.libvirt' and probing guessed raw.
         Automatically detecting the format is dangerous for raw images, write operations on block 0 will be restricted.
         Specify the 'raw' format explicitly to remove the restrictions.
`

Is it possible to extract the individual qcow2 VMs out of the libvirt Whonix-XFCE-15.0.0.0.9.libvirt?

**Comment by bcl** [comment]
Actually they haven't -- you need to follow the instructions to verify the downloaded .xz file and extract the qcow2 images from it -- https://www.whonix.org/wiki/KVM#Download_and_Extract

Note that I don't include those instructions in the README because they may change, no sense in trying to stay in sync with the source documentation.
